// Renders the app icon (web/icon.svg) to the PNGs each platform needs.
// Phone icons and splash screens are then generated by `npx capacitor-assets generate`.
import { chromium } from "playwright";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const svg = readFileSync(join(root, "web/icon.svg"), "utf8");
const glyph = svg.replace(/<rect[^>]*\/>/, ""); // white drawing mark only
const teal = "#0E7C86", dark = "#12151B";
const jobs = [
  ["web/icon-512.png", 512, `<div style="width:512px;height:512px">${svg}</div>`, true],
  ["assets/icon-only.png", 1024, `<div style="width:1024px;height:1024px;background:${teal}">${glyph}</div>`],
  ["assets/icon-foreground.png", 1024, `<div style="width:1024px;height:1024px;padding:192px;box-sizing:border-box">${glyph}</div>`, true],
  ["assets/icon-background.png", 1024, `<div style="width:1024px;height:1024px;background:${teal}"></div>`],
  ["assets/splash.png", 2732, `<div style="width:2732px;height:2732px;background:#F7F8FA;display:grid;place-items:center"><div style="width:420px;height:420px">${svg}</div></div>`],
  ["assets/splash-dark.png", 2732, `<div style="width:2732px;height:2732px;background:${dark};display:grid;place-items:center"><div style="width:420px;height:420px">${svg}</div></div>`],
];
const browser = await chromium.launch();
for (const [out, size, html, transparent] of jobs) {
  const page = await browser.newPage({ viewport: { width: size, height: size } });
  await page.setContent(`<style>html,body{margin:0;background:transparent}svg{width:100%;height:100%;display:block}</style>${html}`);
  await page.screenshot({ path: join(root, out), omitBackground: !!transparent });
  await page.close();
}
await browser.close();
console.log("Icons rendered");
